-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 14:10:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `${dart.sql.db}` ;

-- -----------------------------------------------------
-- Schema dart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `${dart.sql.db}` DEFAULT CHARACTER SET utf8 ;
USE `${dart.sql.db}` ;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`user_group` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`user_group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_description_UNIQUE` (`group_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`user` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL,
  `server_role` SET('USER', 'ROOT') NOT NULL,
  `public_user` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`job` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`job` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `creation_date` DATETIME NULL,
  `user` INT NOT NULL,
  `previous_job` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_user1_idx` (`user` ASC),
  INDEX `fk_job_job1_idx` (`previous_job` ASC),
  CONSTRAINT `fk_job_user1`
    FOREIGN KEY (`user`)
    REFERENCES `${dart.sql.db}`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_job1`
    FOREIGN KEY (`previous_job`)
    REFERENCES `${dart.sql.db}`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`vcf_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`vcf_file` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`vcf_file` (
  `vcf_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `mongo_id` VARCHAR(45) NOT NULL,
  `md5` VARCHAR(32) BINARY NOT NULL,
  `latest_job` INT NOT NULL,
  `creation_time` DATETIME NULL,
  `pipeline_details` VARCHAR(500) NULL,
  `ref_genome` VARCHAR(45) NULL,
  `type` SET('GERMLINE', 'SOMATIC', 'SV') NOT NULL,
  `contigs` TEXT NULL,
  `filter` TEXT NULL,
  PRIMARY KEY (`vcf_id`),
  UNIQUE INDEX `md5_UNIQUE` (`md5` ASC),
  INDEX `fk_vcf_file_job1_idx` (`latest_job` ASC),
  CONSTRAINT `fk_vcf_file_job1`
    FOREIGN KEY (`latest_job`)
    REFERENCES `${dart.sql.db}`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`sample_vcf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`sample_vcf` ;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`sample_vcf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`sample_vcf` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`sample_vcf` (
    `sample_id` INT(11) NOT NULL AUTO_INCREMENT,
    `vcf_id` INT(11) NOT NULL,
    `sample_name` VARCHAR(500) NOT NULL,
    `bam_url` VARCHAR(255) NULL DEFAULT NULL,
    `sample_vcf_url` VARCHAR(255) NULL DEFAULT NULL,
    `sample_coverage_track_url` VARCHAR(255) NULL DEFAULT NULL,
    `sample_coverage_mongo_id` VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (`sample_id`),
    INDEX `fk_sample_has_vcf_file_vcf_file1_idx` (`vcf_id` ASC),
    INDEX `fk_sample_has_vcf_file_sample1_idx` (`sample_id` ASC),
    UNIQUE INDEX `UNIQUENESS` (`vcf_id` ASC, `sample_name` ASC),
    CONSTRAINT `fk_sample_has_vcf_file_vcf_file1`
    FOREIGN KEY (`vcf_id`)
    REFERENCES `${dart.sql.db}`.`vcf_file` (`vcf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `canQuery` TINYINT NOT NULL,
  `canSaveQueryPreset` TINYINT NOT NULL,
  `canValidateVariants` TINYINT NOT NULL,
  `canAnnotatePathogenicity`TINYINT NOT NULL,
  `canSaveQueryPanel` TINYINT NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `canUploadVCF` TINYINT NOT NULL,
  `canSaveReport` TINYINT NOT NULL,
  INDEX `fk_user_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_user_has_group_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqueness` (`user_id` ASC, `group_id` ASC),
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `${dart.sql.db}`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`bed_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`bed_file` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`bed_file` (
  `bed_id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(255) NOT NULL,
  `mongo_id` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `genome` VARCHAR(45) NOT NULL,
  `md5` VARCHAR(32) NOT NULL,
  `latest_job` INT NOT NULL,
  PRIMARY KEY (`bed_id`),
  UNIQUE INDEX `md5_UNIQUE` (`md5` ASC),
  INDEX `fk_bed_file_job1_idx` (`latest_job` ASC),
  CONSTRAINT `fk_bed_file_job1`
    FOREIGN KEY (`latest_job`)
    REFERENCES `${dart.sql.db}`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`bed_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`bed_permissions` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`bed_permissions` (
  `group_id` INT NOT NULL,
  `bed_id` INT NOT NULL,
  `owner` TINYINT NOT NULL,
  PRIMARY KEY (`group_id`, `bed_id`),
  INDEX `fk_group_has_panel_panel1_idx` (`bed_id` ASC),
  INDEX `fk_group_has_panel_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_panel_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_panel_panel1`
    FOREIGN KEY (`bed_id`)
    REFERENCES `${dart.sql.db}`.`bed_file` (`bed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`vcf_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`vcf_permissions` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`vcf_permissions` (
  `group_id` INT NOT NULL,
  `vcf_id` INT NOT NULL,
  `owner` TINYINT NOT NULL,
  PRIMARY KEY (`group_id`, `vcf_id`),
  INDEX `fk_group_has_vcf_vcf1_idx` (`vcf_id` ASC),
  INDEX `fk_group_has_vcf_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_vcf_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_vcf_vcf1`
    FOREIGN KEY (`vcf_id`)
    REFERENCES `${dart.sql.db}`.`vcf_file` (`vcf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`vcf_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`vcf_field` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`vcf_field` (
  `field_id` INT NOT NULL AUTO_INCREMENT,
  `field_path` VARCHAR(255) NOT NULL,
  `field_name` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `vcf_number` SET('A', 'R', 'G', 'VALUE', 'ARRAY') NULL DEFAULT NULL,
  `vcf_type` SET('Integer', 'Float', 'String', 'Character', 'Flag') NULL DEFAULT NULL,
  `internal_type` SET('STRING', 'ARRAY_INT', 'ARRAY_STR', 'ARRAY_DOUBLE', 'INTEGER', 'DOUBLE', 'FLAG') NULL DEFAULT NULL,
  `queryable` TINYINT NOT NULL,
  `possible_values` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`field_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`fields_preset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`fields_preset` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`fields_preset` (
  `user_id` INT NOT NULL,
  `field_id` INT NOT NULL,
  `rank` INT NULL DEFAULT NULL,
  `vcf_type` SET('GERMLINE', 'SOMATIC', 'SV') NOT NULL,
  PRIMARY KEY (`user_id`, `field_id`, `vcf_type`),
  INDEX `fk_fields_preset_vcf_fields1_idx` (`field_id` ASC),
  CONSTRAINT `fk_fields_preset_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `${dart.sql.db}`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fields_preset_vcf_fields1`
    FOREIGN KEY (`field_id`)
    REFERENCES `${dart.sql.db}`.`vcf_field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`panel_presets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`panel_presets` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`panel_presets` (
                                                      `panel_id` INT(11) NOT NULL AUTO_INCREMENT,
                                                      `group_id` INT(11) NOT NULL,
                                                      `panel_mnemonic` VARCHAR(500) NULL DEFAULT NULL,
                                                      `bed_id` INT NULL DEFAULT NULL,
                                                      `genes_hash` INT(11) NULL DEFAULT NULL,
                                                      `genes` TEXT NULL,
                                                      `user_from` INT(11) NOT NULL,
                                                      `date_from` DATETIME NOT NULL,
                                                      `user_to` INT(11) NULL,
                                                      `date_to` DATETIME NULL,
                                                      PRIMARY KEY (`panel_id`),
                                                      INDEX `fk_bed_id_idx` (`bed_id` ASC),
                                                      INDEX `fk_group_idx` (`group_id` ASC),
                                                      INDEX `fk_panel_presets_user_from_idx` (`user_from` ASC),
                                                      INDEX `fk_panel_presets_user_to_idx` (`user_to` ASC),
                                                      CONSTRAINT `fk_group`
                                                          FOREIGN KEY (`group_id`)
                                                              REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_bed_id`
                                                          FOREIGN KEY (`bed_id`)
                                                              REFERENCES `${dart.sql.db}`.`bed_file` (`bed_id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_panel_presets_user_from`
                                                          FOREIGN KEY (`user_from`)
                                                              REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_panel_presets_user_to`
                                                          FOREIGN KEY (`user_to`)
                                                              REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`query_presets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`query_presets` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`query_presets` (
                                                      `query_id` INT(11) NOT NULL AUTO_INCREMENT,
                                                      `group_id` INT(11) NOT NULL,
                                                      `query_mnemonic` VARCHAR(500) NULL DEFAULT NULL,
                                                      `query_hash` INT(11) NOT NULL,
                                                      `rule` MEDIUMBLOB NOT NULL,
                                                      `user_from` INT(11) NOT NULL,
                                                      `date_from` DATETIME NOT NULL,
                                                      `user_to` INT(11) NULL,
                                                      `date_to` DATETIME NULL,
                                                      PRIMARY KEY (`query_id`),
                                                      INDEX `fk_query_presets_group_idx` (`group_id` ASC),
                                                      INDEX `fk_query_presets_user_from_idx` (`user_from` ASC),
                                                      INDEX `fk_query_presets_user_to_idx` (`user_to` ASC),
                                                      CONSTRAINT `fk_query_presets_group`
                                                          FOREIGN KEY (`group_id`)
                                                              REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_query_presets_user_from`
                                                          FOREIGN KEY (`user_from`)
                                                              REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_query_presets_user_to`
                                                          FOREIGN KEY (`user_to`)
                                                              REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`job_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`job_message` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`job_message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `upload_job` INT NOT NULL,
  `type` SET('WARNING', 'INFO', 'ERROR') NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_message_job1_idx` (`upload_job` ASC),
  CONSTRAINT `fk_job_message_job1`
    FOREIGN KEY (`upload_job`)
    REFERENCES `${dart.sql.db}`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`vcf_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`vcf_fields` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`vcf_fields` (
  `vcf_id` INT NOT NULL,
  `field_id` INT NOT NULL,
  PRIMARY KEY (`vcf_id`, `field_id`),
  INDEX `fk_vcf_fields_vcf_field1_idx` (`field_id` ASC),
  CONSTRAINT `fk_vcf_fields_vcf_file1`
    FOREIGN KEY (`vcf_id`)
    REFERENCES `${dart.sql.db}`.`vcf_file` (`vcf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vcf_fields_vcf_field1`
    FOREIGN KEY (`field_id`)
    REFERENCES `${dart.sql.db}`.`vcf_field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`query_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`query_fields` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`query_fields` (
  `query_id` INT NOT NULL,
  `field_id` INT NOT NULL,
  PRIMARY KEY (`query_id`, `field_id`),
  INDEX `fk_vcf_fields_vcf_field1_idx` (`field_id` ASC),
  CONSTRAINT `fk_vcf_fields_vcf_field10`
    FOREIGN KEY (`field_id`)
    REFERENCES `${dart.sql.db}`.`vcf_field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_query_fields_query_preset1`
    FOREIGN KEY (`query_id`)
    REFERENCES `${dart.sql.db}`.`query_presets` (`query_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`variant` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`variant` (
                                                `variant_id` INT NOT NULL AUTO_INCREMENT,
                                                `ref_genome` VARCHAR(45) NOT NULL,
                                                `HGVSg` VARCHAR(450) NOT NULL,
                                                `HGVSc` VARCHAR(450),
                                                `contig` VARCHAR(45) NOT NULL,
                                                `pos` INT NOT NULL,
                                                `gene` VARCHAR(45) NULL,
                                                PRIMARY KEY (`variant_id`),
                                                UNIQUE INDEX `UNIQUENESS` (`ref_genome` ASC, `HGVSg` ASC, `HGVSc` ASC),
                                                INDEX `search_index` (`ref_genome` ASC, `HGVSg` ASC))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`annotation_dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`annotation_dictionary` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`annotation_dictionary` (
                                                              `db_id` INT NOT NULL,
                                                              `annotation_type` VARCHAR(45) NOT NULL,
                                                              `annotation_label` VARCHAR(100) NOT NULL,
                                                              `annotation_description` TEXT NULL,
                                                              `rank` INT NOT NULL,
                                                              PRIMARY KEY (`db_id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`inheritance_dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`inheritance_dictionary` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`inheritance_dictionary` (
                                                               `db_id` INT NOT NULL AUTO_INCREMENT,
                                                               `annotation_type` VARCHAR(45) NOT NULL,
                                                               `inheritance_label` VARCHAR(45) NOT NULL,
                                                               PRIMARY KEY (`db_id`),
                                                               UNIQUE INDEX `UNIQUENESS` (`annotation_type` ASC, `inheritance_label` ASC))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`variant_annotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`variant_annotation` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`variant_annotation` (
                                                           `annotation_id` INT NOT NULL AUTO_INCREMENT,
                                                           `variant_id` INT NOT NULL,
                                                           `group_id` INT NOT NULL,
                                                           `user_from` INT NOT NULL,
                                                           `user_to` INT NULL,
                                                           `date_from` DATETIME NOT NULL,
                                                           `date_to` DATETIME NULL,
                                                           `annotation` INT NOT NULL,
                                                           `health_condition` INT NOT NULL,
                                                           `inheritance_model` INT NOT NULL,
                                                           `supporting_data` MEDIUMBLOB NOT NULL,
                                                           PRIMARY KEY (`annotation_id`),
                                                           INDEX `fk_variant_anno_user_from_idx` (`user_from` ASC),
                                                           INDEX `fk_variant_anno_user_to_idx` (`user_to` ASC),
                                                           INDEX `fk_variant_anno_variant_id_idx` (`variant_id` ASC),
                                                           INDEX `fk_variant_anno_group_idx` (`group_id` ASC),
                                                           INDEX `fk_variant_anno_annotation_idx` (`annotation` ASC),
                                                           INDEX `fk_condition_idx` (`health_condition` ASC),
                                                           INDEX `fk_variant_annotation_inheritance_dictionary1_idx` (`inheritance_model` ASC),
                                                           CONSTRAINT `fk_variant_anno_user_from`
                                                               FOREIGN KEY (`user_from`)
                                                                   REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_variant_anno_user_to`
                                                               FOREIGN KEY (`user_to`)
                                                                   REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_variant_anno_variant_id`
                                                               FOREIGN KEY (`variant_id`)
                                                                   REFERENCES `${dart.sql.db}`.`variant` (`variant_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_variant_anno_group`
                                                               FOREIGN KEY (`group_id`)
                                                                   REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_variant_anno_annotation`
                                                               FOREIGN KEY (`annotation`)
                                                                   REFERENCES `${dart.sql.db}`.`annotation_dictionary` (`db_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_condition`
                                                               FOREIGN KEY (`health_condition`)
                                                                   REFERENCES `${dart.sql.db}`.`condition_dictionary` (`db_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_variant_annotation_inheritance_dictionary1`
                                                               FOREIGN KEY (`inheritance_model`)
                                                                   REFERENCES `${dart.sql.db}`.`inheritance_dictionary` (`db_id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`variant_sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`variant_sample` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`variant_sample` (
                                                       `variant_sample_id` INT NOT NULL AUTO_INCREMENT,
                                                       `sample_id` INT NOT NULL,
                                                       `variant_id` INT NOT NULL,
                                                       PRIMARY KEY (`variant_sample_id`),
                                                       INDEX `fk_variant_sample_variant_id_idx` (`variant_id` ASC),
                                                       INDEX `fk_variant_sample_sample_idx` (`sample_id` ASC),
                                                       UNIQUE INDEX `UNIQUENESS` (`sample_id` ASC, `variant_id` ASC),
                                                       CONSTRAINT `fk_variant_sample_variant_id`
                                                           FOREIGN KEY (`variant_id`)
                                                               REFERENCES `${dart.sql.db}`.`variant` (`variant_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_variant_sample_sample`
                                                           FOREIGN KEY (`sample_id`)
                                                               REFERENCES `${dart.sql.db}`.`sample_vcf` (`sample_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`variant_sample_annotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`variant_sample_annotation` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`variant_sample_annotation` (
                                                                  `annotation_id` INT NOT NULL AUTO_INCREMENT,
                                                                  `variant_sample_id` INT NOT NULL,
                                                                  `group_id` INT NOT NULL,
                                                                  `user_from` INT NOT NULL,
                                                                  `user_to` INT NULL,
                                                                  `date_from` DATETIME NOT NULL,
                                                                  `date_to` DATETIME NULL,
                                                                  `annotation` VARCHAR(45) NOT NULL,
                                                                  PRIMARY KEY (`annotation_id`),
                                                                  INDEX `fk_variant_sample_anno_user_from_idx` (`user_from` ASC),
                                                                  INDEX `fk_variant_sample_anno_user_to_idx` (`user_to` ASC),
                                                                  INDEX `fk_variant_sample_annot_variant_sample_idx` (`variant_sample_id` ASC),
                                                                  INDEX `fk_variant_Sample_annotation_group_idx` (`group_id` ASC),
                                                                  CONSTRAINT `fk_variant_sample_anno_user_from`
                                                                      FOREIGN KEY (`user_from`)
                                                                          REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                          ON DELETE NO ACTION
                                                                          ON UPDATE NO ACTION,
                                                                  CONSTRAINT `fk_variant_sample_anno_user_to`
                                                                      FOREIGN KEY (`user_to`)
                                                                          REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                          ON DELETE NO ACTION
                                                                          ON UPDATE NO ACTION,
                                                                  CONSTRAINT `fk_variant_sample_annot_variant_sample`
                                                                      FOREIGN KEY (`variant_sample_id`)
                                                                          REFERENCES `${dart.sql.db}`.`variant_sample` (`variant_sample_id`)
                                                                          ON DELETE NO ACTION
                                                                          ON UPDATE NO ACTION,
                                                                  CONSTRAINT `fk_variant_Sample_annotation_group`
                                                                      FOREIGN KEY (`group_id`)
                                                                          REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                                          ON DELETE NO ACTION
                                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`condition_dictionary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `${dart.sql.db}`.`condition_dictionary` ;

CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`condition_dictionary` (
                                                   `db_id` INT NOT NULL AUTO_INCREMENT,
                                                   `dictionary_name` VARCHAR(45) NOT NULL,
                                                   `condition_id` VARCHAR(45) NOT NULL,
                                                   `condition_label` VARCHAR(200) NULL,
                                                   `condition_description` MEDIUMTEXT NULL,
                                                   PRIMARY KEY (`db_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`sample_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`sample_condition` (
                                                        `annotation_id` INT NOT NULL AUTO_INCREMENT,
                                                        `sample_id` INT NOT NULL,
                                                        `group_id` INT NOT NULL,
                                                        `user_from` INT NOT NULL,
                                                        `user_to` INT NULL,
                                                        `date_from` DATETIME NOT NULL,
                                                        `date_to` DATETIME NULL,
                                                        `medical_condition` INT NOT NULL,
                                                        PRIMARY KEY (`annotation_id`),
                                                        INDEX `fk_sample_condition_sample_idx` (`sample_id` ASC),
                                                        INDEX `fk_sample_condition_group_idx` (`group_id` ASC),
                                                        INDEX `fk_sample_condition_user_frrom_idx` (`user_from` ASC),
                                                        INDEX `fk_sample_condition_user_to_idx` (`user_to` ASC),
                                                        INDEX `fk_sample_condition_condition_idx` (`medical_condition` ASC),
                                                        CONSTRAINT `fk_sample_condition_sample`
                                                            FOREIGN KEY (`sample_id`)
                                                                REFERENCES `${dart.sql.db}`.`sample_vcf` (`sample_id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_sample_condition_group`
                                                            FOREIGN KEY (`group_id`)
                                                                REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_sample_condition_user_frrom`
                                                            FOREIGN KEY (`user_from`)
                                                                REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_sample_condition_user_to`
                                                            FOREIGN KEY (`user_to`)
                                                                REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_sample_condition_condition`
                                                            FOREIGN KEY (`medical_condition`)
                                                                REFERENCES `${dart.sql.db}`.`condition_dictionary` (`db_id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`report` (
                                               `report_id` INT(11) NOT NULL AUTO_INCREMENT,
                                               `sample_id` INT(11) NOT NULL,
                                               `group_id` INT(11) NOT NULL,
                                               `user_from` INT(11) NOT NULL,
                                               `date_from` DATETIME NOT NULL,
                                               `variants_loaded` INT(11),
                                               `variants_job` INT(11) NULL,
                                               `has_coverage` TINYINT(4) NOT NULL DEFAULT 0,
                                               `coverage_job` INT(11) NULL,
                                               `coverage_loaded` INT(11),
                                               `query_id` INT(11) NOT NULL,
                                               `panel_id` INT(11) NOT NULL,
                                               PRIMARY KEY (`report_id`),
                                               INDEX `fk_report_group1_idx` (`group_id` ASC),
                                               INDEX `fk_report_user2_idx` (`user_from` ASC),
                                               INDEX `fk_report_sample_vcf_idx` (`sample_id` ASC),
                                               INDEX `fk_report_query_idx` (`query_id` ASC),
                                               INDEX `fk_report_panel_idx` (`panel_id` ASC),
                                               INDEX `fk_variant_Job_idx` (`variants_job` ASC),
                                               INDEX `fk_coverage_job_idx` (`coverage_job` ASC),
                                               CONSTRAINT `fk_report_group`
                                                   FOREIGN KEY (`group_id`)
                                                       REFERENCES `${dart.sql.db}`.`user_group` (`group_id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_report_vcf_sample`
                                                   FOREIGN KEY (`sample_id`)
                                                       REFERENCES `${dart.sql.db}`.`sample_vcf` (`sample_id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_report_userFrom`
                                                   FOREIGN KEY (`user_from`)
                                                       REFERENCES `${dart.sql.db}`.`user` (`userId`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_report_query`
                                                   FOREIGN KEY (`query_id`)
                                                       REFERENCES `${dart.sql.db}`.`query_presets` (`query_id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_report_panel`
                                                   FOREIGN KEY (`panel_id`)
                                                       REFERENCES `${dart.sql.db}`.`panel_presets` (`panel_id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_variant_Job`
                                                   FOREIGN KEY (`variants_job`)
                                                       REFERENCES `${dart.sql.db}`.`job` (`id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_coverage_job`
                                                   FOREIGN KEY (`coverage_job`)
                                                       REFERENCES `${dart.sql.db}`.`job` (`id`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`related_sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`related_sample` (
                                                         `report_id` INT(11) NOT NULL,
                                                         `sample_id` INT(11) NOT NULL,
                                                         `affected` TINYINT NOT NULL,
                                                         `sex` VARCHAR(3) NOT NULL,
                                                         PRIMARY KEY (`report_id`,`sample_id`),
                                                         CONSTRAINT `fk_related_sample_report`
                                                             FOREIGN KEY (`report_id`)
                                                                 REFERENCES `${dart.sql.db}`.`report` (`report_id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_related_sample_sample`
                                                             FOREIGN KEY (`sample_id`)
                                                                 REFERENCES `${dart.sql.db}`.`sample_vcf` (`sample_id`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`report_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`report_variant` (
                                                       `report_id` INT NOT NULL,
                                                       `variant_sample` INT NOT NULL,
                                                       `variant_data` MEDIUMBLOB NOT NULL,
                                                       PRIMARY KEY (`report_id`, `variant_sample`),
                                                       INDEX `fk_report_variant_variant_idx` (`variant_sample` ASC),
                                                       CONSTRAINT `fk_report_variant_report`
                                                           FOREIGN KEY (`report_id`)
                                                               REFERENCES `${dart.sql.db}`.`report` (`report_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_report_variant_variant`
                                                           FOREIGN KEY (`variant_sample`)
                                                               REFERENCES `${dart.sql.db}`.`variant_sample` (`variant_sample_id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${dart.sql.db}`.`report_coverage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${dart.sql.db}`.`report_coverage` (
                                                        `coverage_id` INT NOT NULL AUTO_INCREMENT,
                                                        `report_id` INT(11) NOT NULL,
                                                        `coverage_data` MEDIUMBLOB NOT NULL,
                                                        PRIMARY KEY (`coverage_id`),
                                                        INDEX `fk_coverage_report_idx` (`report_id` ASC),
                                                        CONSTRAINT `fk_coverage_report`
                                                            FOREIGN KEY (`report_id`)
                                                                REFERENCES `${dart.sql.db}`.`report` (`report_id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

GRANT SELECT ON TABLE `${dart.sql.db}`.* TO '${dart.sql.user}';
GRANT INSERT, UPDATE ON TABLE `${dart.sql.db}`.* TO '${dart.sql.user}';

GRANT CREATE,INSERT, UPDATE, DELETE, INDEX ON TABLE `${dart.sql.db}`.`CACHE_queries` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`panel_presets` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`query_presets` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`fields_preset` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`user_roles` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`bed_file` TO '${dart.sql.user}';
GRANT DELETE ON TABLE `${dart.sql.db}`.`query_fields` TO '${dart.sql.user}';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
